<MyGrid>
    GridLayout:
        cols:1
        size: root.width, root.height
        GridLayout:
            cols:2
            Label:
                text: "Name: "
            TextInput:
                multiinline: False
            Label:
                text: "sur Name: "
            TextInput:
                multiinline: False
            Label:
                text: "Email: "
            TextInput:
                multiinline: False
        Button:
            text: "Submit"